### ISSUE TITLE
離開頁面前先跳出確認視窗

### ISSUE THREAD

**Issue by lsc36** [iamchucky/PttChrome#14]
使用時偶爾會誤觸上 / 下一頁或書籤導致離開頁面
請問能否先跳出視窗確認是否離開頁面？
如同 Facebook 在編輯動態時，若離開頁面會先行確認

**Comment by iamchucky** [comment]
右鍵開啟後的設定頁面裡面有可以設定離開時先確認
把該選項打勾以後再重新整理PTTCHROME頁面
之後不小心點上一頁或者是書籤應該會跳出詢問確認是否要離開頁面

還是說這個功能在你那邊使用起來沒有用嗎?

**Comment by lsc36** [comment]
看到了，謝謝
