### ISSUE TITLE
在 localhost 應如何測試？

### ISSUE THREAD

**Issue by tsaiid** [iamchucky/PttChrome#20]
Fork 了一份想放在 localhost 測試。
執行 test_server.py 後會一直出現「從 Chrome 程式商店下載」頁面，
查 log 發現是卡在 `chrome.runtime.sendMessage(appId, { action: 'status' }, function(response) {});` 這一段，是因為 chrome 的 extension 有什麼限定嗎？
請問該如何在 localhost 上測試？謝謝。

**Comment by iamchucky** [comment]
要在 localhost 測試的話不能用商店裡的 PttChrome
要把 https://github.com/iamchucky/PttChrome/tree/master 用 chrome://extensions -> Load unpacked extension ... 來加入可以通用 localhost 的 PttChrome
