### ISSUE TITLE
Chrome的側邊欄開啟PttChrome

### ISSUE THREAD

**Issue by vi000246** [iamchucky/PttChrome#36]
如果我從Chrome的側邊欄開啟PttChrome
程式會先關閉當前分頁再開啟PttChrome
但是分頁只有一頁的話就會直接關閉Chrome
想問這個是bug嗎
http://imgur.com/AnBFTI0

**Comment by iamchucky** [comment]
請問這個側邊欄是什麼? 是新版的chrome才有嗎???

**Comment by vi000246** [comment]
看來是我的Speed Dial套件的關係
會將預設的新頁面取代成九宮格+side bar的模式
我再研究看看要怎麼啟動PttChrome的應用程式
謝謝你囉

**Comment by iamchucky** [comment]
你可以直接把https://iamchucky.github.io/PttChrome/index.html加入書籤
之後用這個書籤就可以開了

**Comment by vi000246** [comment]
謝謝 沒想到這點
