### ISSUE TITLE
當持續按著 j, k 來控制上下時，不會連續觸發

### ISSUE THREAD

**Issue by tsaiid** [iamchucky/PttChrome#37]
在 console 下用 ssh 連到 ptt 時，是可以持續按著 'j' 'k' 來做連續向下或向下移動 cursor 的。

**Comment by iamchucky** [comment]
我測試起來沒問題耶, 有沒有什麼情況造成的呢? 你測試的作業系統+Chrome版本是什麼?

**Comment by tsaiid** [comment]
macOS Sierra 10.12.1
Chrome: 版本 54.0.2840.98 (64-bit)

**Comment by iamchucky** [comment]
http://www.idownloadblog.com/2015/01/14/how-to-enable-key-repeats-on-your-mac/
