### ISSUE TITLE
LICENSE 檔案

### ISSUE THREAD

**Issue by robertabcd** [iamchucky/PttChrome#39]
這個 repo 的說明寫 GNU/GPL 但沒有說是那個版本的授權
是否可放個 LICENSE 檔案？

**Comment by iamchucky** [comment]
謝謝提醒, 已加入 LICENSE 檔案

**Comment by iamchucky** [comment]
@robertabcd 我看到你的fork新增加了連線到wss://ws.ptt.cc/bbs

請問PTT官方是不是有打算增加websocket的連線方式? 假如有的話就太好了!!! (由於Google在明年2018就要完全移除Chrome App 而PttChrome需要Chrome App的socket API, 說實在的我一直都在煩惱明年要怎麼繼續提供給使用者PttChrome...)

有沒有什麼我可以幫忙的地方?

**Comment by robertabcd** [comment]
是打算走 websocket，但要先 refactor 到能維護的程度
