### ISSUE TITLE
請問是否能支援搜尋PIXIV？

### ISSUE THREAD

**Issue by abccbaandy** [iamchucky/PttChrome#4]
請問是否能支援搜尋PIXIV？

有點類似google搜尋
'http://www.pixiv.net/member_illust.php?mode=medium&illust_id='+searchTerm

我有clone，試著寫一下，預覽圖
http://i.imgur.com/OpUOdYj.png

但不太了解您的程式，寫完以後只能使用dev.html來開啟...

我是修改pttchrome.js，但要怎麼產生pttchrome.min.js？

直接改index.html裡面的
```javascript
<script type="text/javascript" src="js/pttchrome.min.js"></script>
```
改成
```javascript
<script type="text/javascript" src="js/pttchrome.js"></script>
```
好像也不行XD

原始碼連結
https://github.com/abccbaandy/PttChrome/tree/pixiv

**Comment by iamchucky** [comment]
你好

PIXIV這個應該是看圖的東西吧...
我不知道是否會有許多人用 所以 較好的方式是寫在另外的extension裡, 這樣不只pttchrome可以用, 在網頁上選取字以後也可以用

另外 因為index.html裡的用的pttchrome.min.js是minified的javascript code所以就是包含了許多js/資料夾下的檔案 
要把他concat還有minify的話要用grunt 然後直接在子資料夾下用grunt 

請參考http://gruntjs.com/

**Comment by abccbaandy** [comment]
感謝回應

但不太懂，請問"寫在另外的extension"是什麼意思？

pttchrome的右鍵選單是自己做的吧？一般套件都是加在chrome的預設選單，有辦法兩種相容？

我是想說能不能像ABP寫條件那樣由使用者自行增加右鍵選單，因為還滿多想加的
EX:
goo.gl/XXX
ppt.cc/XXX
之類的....



至於PIXIV，一般網頁應該是沒有需求，通常不會有人只貼那串數字

**Comment by iamchucky** [comment]
"寫在另外的extension" 我是指 "當有字選起來的時候用extension來跳出一個按鈕說用pixiv搜尋"
不過你說的對 由使用者自行增加這些短網址的服務是個不錯的功能
我會考慮加入
我是想類似chrome裡面的chrome://settings/searchEngines的加入/設定方式

假如你有興趣的話想挑戰加入這項功能請讓我知道一下

謝謝

**Comment by abccbaandy** [comment]
ok，我真的滿希望有這功能的，請讓我幫忙吧

現在還保留PCMAN的唯一原因就是要開這些網址...

**Comment by iamchucky** [comment]
好

我的想法是在設定頁面再多加一頁"外掛"(Extensions) 專門給設定這些"快速搜尋"(Quick Search)的捷徑
而設定的方法可以參考chrome裡面的chrome://settings/searchEngines的加入/設定方式
除了中間的"關鍵字"(Keyword) 那欄不用
然後當使用者把字選後按右鍵而且在"快速搜尋"內有設定的話, 功能表內在"在 Google 上搜尋" 的選項下再加一項 快速搜尋 > 的選項 然後滑鼠移到該選項會再依快速搜尋內的設定跳出多個選項, 如 PIVIX, goo.gl, ppt.cc (這些是由使用者在設定裡提供的字串)

至於implementation, 我想先由我來負責設定頁面的加入, 因為那個比較複雜些, 那能不能請你幫忙一下右鍵選單的列出 (假如你很快就弄好的話也可以想一下設定那邊要怎麼弄)

有問題的話也歡迎你隨時提出!
謝謝!

**Comment by abccbaandy** [comment]
您好

請問該從哪邊取得"搜尋"的設定呢？

我目前先寫死在pref.js裡面的
```javascript
function PttChromePref(app, onInitializedCallback) {
  this.searchUrl = ["http://ppt.cc/", "http://0rz.tw/", "http://www.pixiv.net/member_illust.php?mode=medium&illust_id="];
  this.searchName = ["Search ppt.cc for", "Search 0rz.tw for", "Search PIXIV for"];
}
````

原始碼連結
https://github.com/abccbaandy/PttChrome/tree/pixiv

**Comment by iamchucky** [comment]
你可以看看我的最新commit
可以用fetch upstream來更新我的更改
https://help.github.com/articles/syncing-a-fork/

在pref.quickSearches下可以得到 { name: 'xxx', url: 'xxx%s' }

**Comment by abccbaandy** [comment]
更新好了

**Comment by iamchucky** [comment]
我已經把這個功能放上去了

不過我並沒有完全採用你的版本 因為我想假如使用者加入很多個項目的話那可能會導致menu變很長
不過還是謝謝你!
