### ISSUE TITLE
中文字顯示問題

### ISSUE THREAD

**Issue by amowu** [iamchucky/PttChrome#6]
😱

![screen shot 2015-02-05 at 6 20 41 pm](https://cloud.githubusercontent.com/assets/559351/6058643/1fa07712-ad64-11e4-9e9a-20705e2b4ebf.png)

環境：Macbook Pro Yosemite 外接顯示螢幕

**Comment by iamchucky** [comment]
你的字型設定是?

**Comment by iamchucky** [comment]
把字型設定為 SymMingLiu,MingLiU,monospace 看看

**Comment by amowu** [comment]
可以了！
謝謝！
